### ISSUE TITLE
[BUG] Android Requesting Manage Call Permissions

### ISSUE THREAD

**Issue by BasselAshi** [deeeed/expo-audio-stream#162]
## Environment
- expo-audio-stream version: 1.17.0 or above up until the current version of `expo-audio-studio`
- Expo SDK version: 52.0.37
- React Native version: 0.78.0
- Platform & OS version: Android
- Device: Galaxy S22

## Description
We were using 1.14.2 and had `package.lock.json` deleted which caused a version update to `1.17.0`. The newer version started requesting addiitonal permissions upon calling `ExpoAudioStreamModule.requestPermissionsAsync()` for Android. The additional requested permission was to _manage phone calls_. We attempted to update the library to the latest version being `@siteed/expo-audio-studio 2.2.0` but the issue persists.

Happy to provide additional details but this might be helpful enough at the moment.

**Comment by deeeed** [comment]
Should be fixed with `2.3.0`, please check

**Comment by BasselAshi** [comment]
I have just upgraded to `2.3.0` and rebuilt with Expo. The problem is still there.
